name: cross_fund
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  get: ^4.6.5
  textless: ^6.6.6
  loading_animation_widget: ^1.2.0+3
  fluttertoast: ^8.1.1
  line_icons: ^2.0.1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.10.0
  build_runner:
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
